# Generated by Django 2.1.4 on 2018-12-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='long_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
