# Generated by Django 2.1.5 on 2019-01-24 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_season_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ('-name',)},
        ),
    ]
