# Generated by Django 2.1.5 on 2019-01-25 03:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190123_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('upcoming', models.SmallIntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True)),
                ('captial', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('rarity', models.CharField(blank=True, max_length=50, null=True)),
                ('obtained', models.CharField(blank=True, max_length=50, null=True)),
                ('obtained_type', models.CharField(blank=True, max_length=50, null=True)),
                ('featured', models.SmallIntegerField(blank=True, null=True)),
                ('refundable', models.SmallIntegerField(blank=True, null=True)),
                ('ratings', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('last_update', models.CharField(blank=True, max_length=50, null=True)),
                ('is_upcoming', models.BooleanField(default=False)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('image_transparent', models.URLField(blank=True, null=True)),
                ('image_background', models.URLField(blank=True, null=True)),
                ('image_information', models.URLField(blank=True, null=True)),
                ('image_featured_transparent', models.URLField(blank=True, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
