# Generated by Django 2.1.5 on 2019-01-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ('number',)},
        ),
        migrations.AlterField(
            model_name='season',
            name='number',
            field=models.SmallIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
