# Generated by Django 2.1.5 on 2019-01-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190124_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='featured',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='refundable',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
