# Generated by Django 2.1.5 on 2019-01-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190124_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_upcoming',
            field=models.BooleanField(default=False),
        ),
    ]
