# Generated by Django 2.1.4 on 2018-12-12 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerstats',
            options={'ordering': ('-date_added',), 'verbose_name_plural': 'player statuses'},
        ),
    ]
