# Generated by Django 2.1.4 on 2018-12-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='platforms',
            field=models.ManyToManyField(blank=True, null=True, related_name='players', to='core.Platform'),
        ),
        migrations.AlterField(
            model_name='player',
            name='seasons',
            field=models.ManyToManyField(blank=True, null=True, related_name='players', to='core.Season'),
        ),
    ]
