# Generated by Django 2.1.4 on 2018-12-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20181212_0101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerstats',
            options={'ordering': ('date_added',), 'verbose_name_plural': 'player statuses'},
        ),
        migrations.AddField(
            model_name='player',
            name='friend',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
