# Generated by Django 2.1.5 on 2019-01-22 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('players', '0005_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='window',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='core.Season'),
        ),
    ]
