# Generated by Django 2.1.5 on 2019-01-24 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_playerstats_window'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerstats',
            options={'ordering': ('-date_added',), 'verbose_name_plural': 'player statuses'},
        ),
    ]
