# Generated by Django 2.1.5 on 2019-01-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_auto_20190123_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='source',
            field=models.CharField(choices=[('public_api', 'Public API'), ('fortnite_tracker', 'Fortnite Tracker')], default='fortnite_tracker', max_length=500),
            preserve_default=False,
        ),
    ]
